---
- hosts: all
  remote_user: yossarian
  vars_files:
    - secrets.yml
  become: yes
  become_method: sudo
  tasks:
  - name: login to docker registry
    docker_login:
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      email: "{{ docker_hub_email }}"
  - name: create custom container
    docker_container:
      name: customContainer
      image: sexsmith/k8stesting
      state: started
      exposed_ports:
        - 80
      ports:
        "80:80"

